### ISSUE TITLE
Acceptance Test: Middle reflection

### ISSUE THREAD

**Issue by eneadodi** [david-fisher/320-F20-Track-III#149]

**Comment by benjaminxu251** [comment]
Link to document: [https://docs.google.com/document/d/1nP6-_5jQjpxSVg7CIa-IDCZ1OqS0TmxQv5U7-6yGaQQ/edit#](https://docs.google.com/document/d/1nP6-_5jQjpxSVg7CIa-IDCZ1OqS0TmxQv5U7-6yGaQQ/edit#heading=h.mhejk9hjrfkb)
Section title: "Part 15: Add Middle Reflection Acceptance Test"

**Comment by benjaminxu251** [comment]
Link to document: [https://docs.google.com/document/d/1nP6-_5jQjpxSVg7CIa-IDCZ1OqS0TmxQv5U7-6yGaQQ/edit#](https://docs.google.com/document/d/1nP6-_5jQjpxSVg7CIa-IDCZ1OqS0TmxQv5U7-6yGaQQ/edit#heading=h.mhejk9hjrfkb)
Section title: "Part 2: Log-in Acceptance Test"
